/* ---------- INTERNAL APPS ---------- */
function getSpotifyHTML(){
  var html = '<!DOCTYPE html>'
  + '<html lang="en">'
  + '<head>'
  + '<meta charset="UTF-8">'
  + '<meta name="viewport" content="width=device-width, initial-scale=1.0">'
  + '<title>Spotify</title>'
  + '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">'
  + '<style>'
  + '*{margin:0;padding:0;box-sizing:border-box;font-family:"Segoe UI",system-ui,-apple-system,sans-serif;}'
  + 'body{background:#000;color:#fff;height:100vh;overflow:hidden;display:flex;flex-direction:column;}'
  + '.topbar{height:60px;background:#000;display:flex;align-items:center;gap:16px;padding:0 24px;flex-shrink:0;border-bottom:1px solid #1a1a1a;}'
  + '.brand{display:flex;align-items:center;gap:10px;font-weight:800;font-size:20px;}'
  + '.brand i{color:#1DB954;font-size:26px;}'
  + '.nav-pills{display:flex;gap:8px;margin-left:8px;}'
  + '.nav-pill{background:#1a1a1a;border:none;color:#aaa;padding:8px 16px;border-radius:20px;cursor:pointer;font-size:13px;font-weight:600;transition:.15s;display:flex;align-items:center;gap:8px;}'
  + '.nav-pill:hover{background:#2a2a2a;color:#fff;}'
  + '.nav-pill.active{background:#fff;color:#000;}'
  + '.nav-pill.active i{color:#000;}'
  + '.main{flex:1;overflow-y:auto;padding:24px 24px 120px 24px;background:linear-gradient(180deg,#1a1a1a 0%,#000 400px);}'
  + '.main::-webkit-scrollbar{width:10px;}'
  + '.main::-webkit-scrollbar-thumb{background:#333;border-radius:5px;}'
  + '.section-title{font-size:22px;font-weight:700;margin-bottom:16px;}'
  + '.hero{display:flex;align-items:flex-end;gap:24px;padding:20px 0 30px 0;margin-bottom:20px;}'
  + '.hero-icon{width:180px;height:180px;border-radius:6px;background:linear-gradient(135deg,#4a1e9e 0%,#8b5cf6 50%,#ec4899 100%);display:flex;align-items:center;justify-content:center;box-shadow:0 20px 50px rgba(0,0,0,.6);flex-shrink:0;}'
  + '.hero-icon i{font-size:70px;color:#fff;}'
  + '.hero-info{display:flex;flex-direction:column;gap:8px;}'
  + '.hero-info .type{font-size:12px;text-transform:uppercase;letter-spacing:1px;font-weight:700;color:#aaa;}'
  + '.hero-info .name{font-size:64px;font-weight:900;line-height:1;}'
  + '.hero-info .meta{font-size:14px;color:#aaa;margin-top:6px;}'
  + '.track-list{display:flex;flex-direction:column;gap:2px;}'
  + '.track{display:grid;grid-template-columns:32px 48px 1fr 1fr 60px 40px;align-items:center;gap:14px;padding:10px 14px;border-radius:6px;cursor:pointer;transition:background .12s;}'
  + '.track:hover{background:#1a1a1a;}'
  + '.track.playing .t-title{color:#1DB954;}'
  + '.track.playing .t-num{color:#1DB954;}'
  + '.t-num{color:#888;font-size:14px;text-align:right;}'
  + '.t-art{width:44px;height:44px;border-radius:4px;object-fit:cover;background:#333;flex-shrink:0;display:flex;align-items:center;justify-content:center;}'
  + '.t-art i{color:#666;font-size:18px;}'
  + '.t-info{display:flex;flex-direction:column;min-width:0;}'
  + '.t-title{font-size:15px;font-weight:500;color:#fff;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}'
  + '.t-artist{font-size:13px;color:#888;margin-top:2px;}'
  + '.t-album{font-size:13px;color:#888;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}'
  + '.t-dur{font-size:13px;color:#888;text-align:right;}'
  + '.t-actions{display:flex;align-items:center;justify-content:center;}'
  + '.heart-btn{background:none;border:none;color:#888;cursor:pointer;font-size:16px;padding:6px;border-radius:50%;transition:.15s;}'
  + '.heart-btn:hover{color:#fff;transform:scale(1.1);}'
  + '.heart-btn.liked{color:#1DB954;}'
  + '.empty-state{text-align:center;padding:80px 20px;color:#666;}'
  + '.empty-state i{font-size:48px;margin-bottom:16px;color:#333;}'
  + '.empty-state p{font-size:15px;}'
  + '.now-playing{position:absolute;bottom:0;left:0;right:0;height:90px;background:#181818;border-top:1px solid #282828;display:grid;grid-template-columns:1fr 2fr 1fr;align-items:center;padding:0 16px;gap:16px;z-index:10;}'
  + '.np-left{display:flex;align-items:center;gap:14px;min-width:0;}'
  + '.np-art{width:56px;height:56px;border-radius:6px;object-fit:cover;background:#333;display:flex;align-items:center;justify-content:center;flex-shrink:0;}'
  + '.np-art i{color:#666;font-size:20px;}'
  + '.np-info{display:flex;flex-direction:column;min-width:0;}'
  + '.np-title{font-size:14px;font-weight:600;color:#fff;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}'
  + '.np-artist{font-size:12px;color:#888;margin-top:2px;}'
  + '.np-center{display:flex;flex-direction:column;align-items:center;gap:6px;max-width:600px;margin:0 auto;width:100%;}'
  + '.np-controls{display:flex;align-items:center;gap:18px;}'
  + '.ctrl{background:none;border:none;color:#aaa;cursor:pointer;font-size:16px;padding:4px;display:flex;align-items:center;justify-content:center;}'
  + '.ctrl:hover{color:#fff;transform:scale(1.08);}'
  + '.ctrl.play-btn{background:#fff;color:#000;width:34px;height:34px;border-radius:50%;font-size:14px;}'
  + '.repeat-btn{font-size:14px;color:#888;transition:.15s;}'
  + '.repeat-btn:hover{color:#fff;}'
  + '.repeat-btn.active{color:#1DB954;}'
  + '.repeat-btn.active::after{content:"";position:absolute;bottom:-2px;left:50%;transform:translateX(-50%);width:4px;height:4px;border-radius:50%;background:#1DB954;}'
  + '.repeat-btn{position:relative;}'
  + '.np-bar{display:flex;align-items:center;gap:10px;width:100%;font-size:11px;color:#888;}'
  + '.bar-bg{flex:1;height:4px;background:#4d4d4d;border-radius:2px;cursor:pointer;position:relative;}'
  + '.bar-fill{position:absolute;top:0;left:0;height:100%;background:#fff;border-radius:2px;width:0%;}'
  + '.np-right{display:flex;align-items:center;justify-content:flex-end;gap:8px;}'
  + '.vol-bg{width:90px;height:4px;background:#4d4d4d;border-radius:2px;cursor:pointer;position:relative;}'
  + '.vol-fill{position:absolute;top:0;left:0;height:100%;background:#fff;border-radius:2px;width:70%;}'
  + '.liked-header{display:flex;align-items:center;gap:14px;margin-bottom:24px;}'
  + '.liked-header .back{background:#1a1a1a;border:none;color:#fff;width:36px;height:36px;border-radius:50%;cursor:pointer;display:flex;align-items:center;justify-content:center;}'
  + '</style>'
  + '</head>'
  + '<body>'
  + '<div class="topbar"><div class="brand"><i class="fab fa-spotify"></i> Synify</div>'
  + '<div class="nav-pills">'
  + '<button class="nav-pill active" id="nav-home"><i class="fas fa-home"></i> Home</button>'
  + '<button class="nav-pill" id="nav-liked"><i class="fas fa-heart"></i> Liked Songs</button>'
  + '</div></div>'
  + '<div class="main" id="main"></div>'
  + '<div class="now-playing">'
  + '<div class="np-left"><div class="np-art" id="np-art"><i class="fas fa-music"></i></div>'
  + '<div class="np-info"><div class="np-title" id="np-title">No track playing</div>'
  + '<div class="np-artist" id="np-artist">—</div></div></div>'
  + '<div class="np-center"><div class="np-controls">'
  + '<button class="ctrl" id="btn-prev"><i class="fas fa-step-backward"></i></button>'
  + '<button class="ctrl play-btn" id="btn-play"><i class="fas fa-play" id="play-icon"></i></button>'
  + '<button class="ctrl" id="btn-next"><i class="fas fa-step-forward"></i></button>'
  + '<button class="ctrl repeat-btn" id="btn-repeat" title="Repeat"><i class="fas fa-redo"></i></button>'
  + '</div><div class="np-bar"><span id="time-cur">0:00</span>'
  + '<div class="bar-bg" id="bar-bg"><div class="bar-fill" id="bar-fill"></div></div>'
  + '<span id="time-tot">0:00</span></div></div>'
  + '<div class="np-right"><i class="fas fa-volume-up" style="color:#888;font-size:14px;"></i>'
  + '<div class="vol-bg" id="vol-bg"><div class="vol-fill" id="vol-fill"></div></div></div>'
  + '</div>'
  + '<script>'
  + 'var TRACKS=['
+ '{id:"east-coast",title:"East Coast",artist:"Alex G",album:"Single",duration:"2:31",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/east%20coast.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20004359.png"},'
+ '{id:"money-longer",title:"Money Longer",artist:"Lil Uzi Vert",album:"Lil Uzi Vert vs. The World",duration:"3:19",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Money%20Longer%20-%20Lil%20Uzi%20Vert%20%20Lyrics.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20004525.png"},'
+ '{id:"on-me",title:"On Me",artist:"Lil Baby",album:"Single/wait about 10 seconds for the song to play will fix in the future!",duration:"2:45",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Lil%20Baby%20-%20On%20Me.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/lilbabyonmecoveralbum.png"},'
+ '{id:"Rider",title:"Rider-remix",artist:"45GBaby-Chicken P",album:"Remix",duration:"2:53",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/45GBaby.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20005316.png"},'
+ '{id:"On the block",title:"On The Block",artist:"Lil maru",album:"Single",duration:"3:36",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/On%20The%20Block.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20193658.png"},'
+ '{id:"Poured",title:"Poured",artist:"Lil Uzi Vert",album:"Maverick Almost Forever EP",duration:"3:00",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Lil%20Uzi%20Vert%20-%20Poured%20-%20%5BOfficial%20Visualizer%5D.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20193940.png"},'
+ '{id:"Fulrera",title:"Fuera Del Planeta",artist:"Eloy",album:"Mix",duration:"3:42",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Fuera%20Del%20Planeta%20(Remix).mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20194912.png"},'
+ '{id:"Myron",title:"Myron",artist:"Lil Uzi Vert",album:"None",duration:"3:45",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Lil%20Uzi%20Vert%20-%20Myron%20%5BOfficial%20Audio%5D.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20195209.png"},'
+ '{id:"em5",title:"Bad (2012 Remaster)",artist:"Michael Jackson",album:"None",duration:"4:07",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Bad%20(2012%20Remaster).mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20195402.png"},'
+ '{id:"em4",title:"Dead Fresh",artist:"Lil Baby",album:"None",duration:"2:48",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Lil%20Baby%20-%20Dead%20Fresh.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20195712.png"},'
+ '{id:"em3",title:"Homecoming",artist:"Lil Uzi Vert",album:"Eternal Atake",duration:"3:34",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Lil%20Uzi%20Vert%20-%20Homecoming%20%5BOfficial%20Audio%5D.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20195814.png"},'
+ '{id:"em2",title:"Harvey",artist:"Alex G",album:"None",duration:"1:39",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Harvey.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20200107.png"},'
+ '{id:"fas",title:"Welcome To My Crib",artist:"Randy Nota Loca",album:"None",duration:"4:07",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Welcome%20To%20My%20Crib.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20204144.png"},'
+ '{id:"asf",title:"16 Mirrors",artist:"Alex G",album:"None",duration:"1:27",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/16%20Mirrors.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20204414.png"},'
+ '{id:"asd",title:"North Pole",artist:"Boohavinn",album:"None",duration:"1:27",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Boohavinn%20-%20North%20Pole%20(Official%20Video).mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20204655.png"},'
+'{id:"sad",title:"90mh",artist:"Trefuego",album:"None",duration:"2:21",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Trefuego%20-%2090mh%20%20Lyrics.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20204925.png"},'
+ '{id:"sad3",title:"Trusted you",artist:"DTG",album:"None",duration:"3:25",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Trusted%20You..mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-16%20205115.png"},'
+ '{id:"sad34",title:"Welcome To My Crib",artist:"Eclipse",album:"None",duration:"1:25",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Welcome%20To%20My%20Crib.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-17%20221156.png"},'
+ '{id:"sad354",title:"tesla -slowed electro mix",artist:"Fixupboy",album:"None",duration:"2:34",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/tesla%20(slowed%20electro%20mix).mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-17%20221929.png"},'
+ '{id:"sad3445525",title:"Already",artist:"Kodak Black",album:"None",duration:"4:01",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Already.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-17%20222229.png"},'
+ '{id:"sad4551sss",title:"Kriss Vecc",artist:"MAF Teeski",album:"None",duration:"2:45",url:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/MAF%20Teeski%20-%20Kriss%20Vecc%20(feat.%20BAK%20Jay)%20%5BOfficial%20Audio%5D.mp3",cover:"https://cdn.jsdelivr.net/gh/taskmaster773/2wafawwfa@main/Screenshot%202026-09-17%20222722.png"},'
+ '];'
  + 'var likedIds=new Set();'
  + 'try{var stored=localStorage.getItem("synify_liked");if(stored)likedIds=new Set(JSON.parse(stored));}catch(e){}'
  + 'function saveLikes(){try{localStorage.setItem("synify_liked",JSON.stringify([...likedIds]));}catch(e){}}'
  + 'var currentTrackId=null,isPlaying=false,view="home";'
  + 'var audio=new Audio();audio.volume=0.7;'
  + 'var mainEl=document.getElementById("main");'
  + 'var npArt=document.getElementById("np-art"),npTitle=document.getElementById("np-title"),npArtist=document.getElementById("np-artist");'
  + 'var playIcon=document.getElementById("play-icon"),barFill=document.getElementById("bar-fill"),barBg=document.getElementById("bar-bg");'
  + 'var timeCur=document.getElementById("time-cur"),timeTot=document.getElementById("time-tot");'
  + 'var volBg=document.getElementById("vol-bg"),volFill=document.getElementById("vol-fill");'
  + 'function fmt(s){if(!isFinite(s)||isNaN(s))return "0:00";var m=Math.floor(s/60),sec=Math.floor(s%60);return m+":"+String(sec).padStart(2,"0");}'
  + 'function trackById(id){for(var i=0;i<TRACKS.length;i++)if(TRACKS[i].id===id)return TRACKS[i];return null;}'
  + 'function render(){if(view==="liked")renderLikedView();else renderHomeView();'
  + 'document.getElementById("nav-home").classList.toggle("active",view==="home");'
  + 'document.getElementById("nav-liked").classList.toggle("active",view==="liked");}'
  + 'function renderHomeView(){var likedCount=likedIds.size;var html="";'
  + 'if(likedCount>0){html+=\'<div class="hero" id="hero-liked" style="cursor:pointer;"><div class="hero-icon"><i class="fas fa-heart"></i></div><div class="hero-info"><span class="type">Playlist</span><span class="name">Liked Songs</span><span class="meta">\'+likedCount+\' song\'+(likedCount===1?"":"s")+\'</span></div></div>\';}'
  + 'html+=\'<div class="section-title">All Songs</div><div class="track-list">\';'
  + 'for(var i=0;i<TRACKS.length;i++)html+=trackRowHTML(TRACKS[i],i);'
  + 'html+="</div>";mainEl.innerHTML=html;attachTrackHandlers();'
  + 'var hl=document.getElementById("hero-liked");if(hl)hl.onclick=function(){view="liked";render();};}'
  + 'function renderLikedView(){var liked=[];for(var i=0;i<TRACKS.length;i++)if(likedIds.has(TRACKS[i].id))liked.push(TRACKS[i]);'
  + 'var html=\'<div class="liked-header"><button class="back" id="back-btn"><i class="fas fa-arrow-left"></i></button><div class="section-title" style="margin:0;">Liked Songs</div></div>\';'
  + 'if(liked.length===0){html+=\'<div class="empty-state"><i class="fas fa-heart"></i><p>Songs you like will appear here</p><p style="font-size:13px;margin-top:8px;">Tap the heart on any song to save it.</p></div>\';}'
  + 'else{html+=\'<div class="track-list">\';for(var i=0;i<liked.length;i++)html+=trackRowHTML(liked[i],i);html+="</div>";}'
  + 'mainEl.innerHTML=html;attachTrackHandlers();'
  + 'var bb=document.getElementById("back-btn");if(bb)bb.onclick=function(){view="home";render();};}'
  + 'function trackRowHTML(t,index){var isLiked=likedIds.has(t.id);var isCurrent=currentTrackId===t.id;'
  + 'var cover=t.cover?\'<img class="t-art" src="\'+t.cover+\'" alt="">\':\'<div class="t-art"><i class="fas fa-music"></i></div>\';'
  + 'var numHtml=isCurrent&&isPlaying?\'<i class="fas fa-volume-up" style="font-size:12px;"></i>\':(index+1);'
  + 'return \'<div class="track \'+(isCurrent?"playing":"")+\'" data-id="\'+t.id+\'">\''
  + '+\'<span class="t-num">\'+numHtml+\'</span>\'+cover'
  + '+\'<div class="t-info"><span class="t-title">\'+t.title+\'</span><span class="t-artist">\'+t.artist+\'</span></div>\''
  + '+\'<span class="t-album">\'+t.album+\'</span><span class="t-dur">\'+t.duration+\'</span>\''
  + '+\'<div class="t-actions"><button class="heart-btn \'+(isLiked?"liked":"")+\'" data-heart="\'+t.id+\'"><i class="\'+(isLiked?"fas":"far")+\' fa-heart"></i></button></div>\''
  + '+\'</div>\';}'
  + 'function attachTrackHandlers(){var rows=document.querySelectorAll(".track");for(var i=0;i<rows.length;i++){rows[i].addEventListener("click",function(e){if(e.target.closest(".heart-btn"))return;playTrack(this.dataset.id);});}'
  + 'var hearts=document.querySelectorAll(".heart-btn");for(var j=0;j<hearts.length;j++){hearts[j].addEventListener("click",function(e){e.stopPropagation();toggleLike(this.dataset.heart);});}}'
  + 'function toggleLike(id){if(likedIds.has(id))likedIds.delete(id);else likedIds.add(id);saveLikes();render();}'
  + 'function playTrack(id){var t=trackById(id);if(!t)return;'
  + 'if(currentTrackId===id){if(audio.paused)audio.play();else audio.pause();return;}'
  + 'currentTrackId=id;audio.src=t.url;audio.play().catch(function(){});updateNowPlaying();render();}'
  + 'function updateNowPlaying(){var t=trackById(currentTrackId);'
  + 'if(!t){npTitle.textContent="No track playing";npArtist.textContent="—";npArt.innerHTML=\'<i class="fas fa-music"></i>\';return;}'
  + 'npTitle.textContent=t.title;npArtist.textContent=t.artist;'
  + 'if(t.cover){npArt.innerHTML=\'<img src="\'+t.cover+\'" style="width:100%;height:100%;border-radius:6px;object-fit:cover;">\';}'
  + 'else{npArt.innerHTML=\'<i class="fas fa-music"></i>\';}}'
  + 'function playNext(){if(!currentTrackId){if(TRACKS[0])playTrack(TRACKS[0].id);return;}'
  + 'var idx=0;for(var i=0;i<TRACKS.length;i++)if(TRACKS[i].id===currentTrackId)idx=i;'
  + 'var next=TRACKS[(idx+1)%TRACKS.length];if(next)playTrack(next.id);}'
  + 'function playPrev(){if(!currentTrackId){if(TRACKS[0])playTrack(TRACKS[0].id);return;}'
  + 'var idx=0;for(var i=0;i<TRACKS.length;i++)if(TRACKS[i].id===currentTrackId)idx=i;'
  + 'var prev=TRACKS[(idx-1+TRACKS.length)%TRACKS.length];if(prev)playTrack(prev.id);}'
  + 'audio.addEventListener("play",function(){isPlaying=true;playIcon.className="fas fa-pause";render();});'
  + 'audio.addEventListener("pause",function(){isPlaying=false;playIcon.className="fas fa-play";render();});'
  + 'audio.addEventListener("timeupdate",function(){if(audio.duration&&isFinite(audio.duration)){barFill.style.width=((audio.currentTime/audio.duration)*100)+"%";timeCur.textContent=fmt(audio.currentTime);timeTot.textContent=fmt(audio.duration);}});'
  + 'audio.addEventListener("loadedmetadata",function(){timeTot.textContent=fmt(audio.duration);});'
  + 'var repeatOn=false;'
  + 'audio.addEventListener("ended",function(){if(repeatOn){audio.currentTime=0;audio.play().catch(function(){});}else{playNext();}});'
  + 'document.getElementById("btn-repeat").onclick=function(){repeatOn=!repeatOn;this.classList.toggle("active",repeatOn);};'
  + 'document.getElementById("btn-play").onclick=function(){if(!currentTrackId){if(TRACKS[0])playTrack(TRACKS[0].id);return;}if(audio.paused)audio.play();else audio.pause();};'
  + 'document.getElementById("btn-next").onclick=playNext;'
  + 'document.getElementById("btn-prev").onclick=function(){if(audio.currentTime>3){audio.currentTime=0;}else playPrev();};'
  + 'barBg.addEventListener("click",function(e){if(!audio.duration||!isFinite(audio.duration))return;var r=barBg.getBoundingClientRect();var pct=(e.clientX-r.left)/r.width;audio.currentTime=pct*audio.duration;});'
  + 'volBg.addEventListener("click",function(e){var r=volBg.getBoundingClientRect();var pct=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));audio.volume=pct;volFill.style.width=(pct*100)+"%";});'
  + 'document.getElementById("nav-home").onclick=function(){view="home";render();};'
  + 'document.getElementById("nav-liked").onclick=function(){view="liked";render();};'
  + 'render();'
  + '<\/script>'
  + '</body>'
  + '</html>';
  return html;
}
